name: Project Testing
run-name: ${{ github.actor }} is testing his project....
on:
  push:
    branches:
      - main
  
jobs:
  project-feedback:
    runs-on: ubuntu-latest

    steps:
      - name: Kaggle Username Checking
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        if: ${{ env.KAGGLE_USERNAME == null }}
        run: echo "Kaggle Username is not set. Please set it in the repository secrets OR Go to \"Settings > Environments\" to create it"
            
      - name: Kaggle Key Checking
        env:
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        if: ${{ env.KAGGLE_KEY == null }}
        run: echo "Kaggle Key is not set. Please set it in the repository secrets OR Go to \"Settings > Environments\" to create it"

      - name: Checkout
        uses: actions/checkout@v3

      # Install Python
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Kaggle authentication
        shell: bash
        run: |
          echo '{
            "username": "${{ secrets.KAGGLE_USERNAME }}",
            "key": "${{ secrets.KAGGLE_KEY }}"
          }' > kaggle.json
          mkdir -p /home/runner/.kaggle
          mv kaggle.json /home/runner/.kaggle/
          chmod 600 /home/runner/.kaggle/kaggle.json
          echo "Kaggle authentication is done"

      # Set environment variables for Kaggle credentials
      - name: Set Kaggle Environment Variables
        run: |
          echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}" >> $GITHUB_ENV
          echo "KAGGLE_KEY=${{ secrets.KAGGLE_KEY }}" >> $GITHUB_ENV

      # Run exercise feedback
      - name: Make test running
        run: chmod +x /home/runner/work/Data_Science-MADE/Data_Science-MADE/project/test.sh

      - name: Run Tests
        run: /home/runner/work/Data_Science-MADE/Data_Science-MADE/project/test.sh
